[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_BASE_PATH = "/"

# SPA rewrite: rewrite todo lo que NO empiece por "/.netlify/" a index.html
[[redirects]]
  from = "^/(?!\\.netlify/).*"
  to = "/index.html"
  status = 200